### ISSUE TITLE
Different area not applying 

### ISSUE THREAD

**Issue by Axilotl17** [9tin9tin9/Mac-trackpad-mapper#1]
I used the default code example for top right corner (and I changed resolution) and It still maps the entire trackpad to the entire screen. 
[settings.h.zip](https://github.com/9tin9tin9/Mac-trackpad-mapper/files/10144429/settings.h.zip)

**Comment by lokxii** [comment]
Did you recompile and rerun the binary?
I have made quite a lot of changes recently and could you please also try the new version?

**Comment by Axilotl17** [comment]
Yes, will do when I can.

**Comment by Axilotl17** [comment]
Alright, a few things, regarding these files: 
<img width="759" alt="Screen Shot 2022-12-06 at 10 29 58 AM" src="https://user-images.githubusercontent.com/78441708/205992667-3c4b181c-79c3-4e9c-9ecd-5a87ec796d5f.png">
 
Running the "Trackpad Mapper.app" file appears to do nothing. it just opens the app but doesn't change anything. 

Running the "trackpad_mapper" app just crashes and spits out this macos crash log:
[crash.txt](https://github.com/9tin9tin9/Mac-trackpad-mapper/files/10169266/crash.txt)
I realize maybe this wasn't meant to be run, but then maybe don't put it here or anywhere? I'm unsure what the point of it is, to be honest. 

Finally, running the last file is working perfectly; the mapping function works after rebuilding, and when rebuilding with `make util_release install_util_update` it is the only file that is updated.

**Comment by lokxii** [comment]
I should have mentioned in the README that absolutely tracking is turned off by default. You have to click on the icon on status bar, and choose "Start absolute tracking" on the menu appeared. I will add this to README later.
Those binary files are not meant to be run directly. I should have hidden them in a bin folder inside build.
I haven't looked into your crash log yet. Gonna investigate it later

**Comment by Axilotl17** [comment]
I... see a lack of menu when opening the `Trackpad Mapper.app` file. it appears nothing happens. It asks for accessibility features then nothing. 

> click on the icon on status bar

what does this mean? what icon? I don't see any useful menu on clicking on the item in the dock. (item launched from `Trackpad Mapper.app`)

**Comment by lokxii** [comment]
Not the icon in the dock. The icon on status bar at the top of the screen. Next to those date/time/Wifi/battery icons

I think I should also add some photos and gif on the README later to show the usage

**Comment by Axilotl17** [comment]
Ahhh yes I see it! 
however, you need to build with `make release` AFTER deleting `Trackpad Mapper.app` to change how it is mapped. `trackpad_mapper_util` however gets updated with `make release` without deleting it. 
for some reason `make release` doesn't change the existing  `Trackpad Mapper.app`

**Comment by Axilotl17** [comment]
Alright I've added a PR to fix a few small things, but I left out the details about the status bar and such as I suspect you may want to edit them. 

Thanks for your help! I will be making a new issue to discuss different things, but I'll mark this as closed.

**Comment by lokxii** [comment]
The existing Trackpad Mapper.app do you mean the one in build folder or application folder?
`make release` just compiles the app. You have to quit and rerun the app for the changes to apply. Therefore I provided `make install_util_update` to only update the util binary in the app bundle inside `Applications` folder, so that you only need to Stop and Start absolute tracking without quitting the app.
If you are frequently changing the mapping rule, I would recommend you to put `Trackpad Mapper.app` inside Applications folder, and run `make util_release install_util_update` every time you make changes

**Comment by Axilotl17** [comment]
I have no `Trackpad Mapper.app` in the application folder. why do you recommend I move it there?

the one in the build folder must be deleted, then `make release` must be run again to change the map... unless I'm doing something wrong. 

side note, do you have a discord or slack channel or some other method I can communicate quicker with and send you videos of issues or whatnot?

**Comment by Axilotl17** [comment]
> unless I'm doing something wrong.

I was doing something wrong. maybe it was moving `Trackpad Mapper.app` to Applications like you suggested that fixed it...
