### ISSUE TITLE
One more thing

### ISSUE THREAD

**Issue by e-su** [9tin9tin9/Mac-trackpad-mapper#12]
I implemented tapping the left or right side of the trackpad to generate the specified event. But the gestures of the system are still there. I have no idea how to disable system mouse click event.

**Comment by 9tin9tin9** [comment]
You need to filter system mouse click events in CG event tap. You can identify your own mouse events by tagging a special number in user field of your generated mouse event.

You tap into the CG event tap with kCGEventTapOptionDefault and hook a callback. In the callback you identify your own events and filter out system mouse events by only returning your mouse events.

You may want to look at `hookMouseCallback()` to see how I set up a filter

**Comment by lokxii** [comment]
Do you mean gesture events or mouse click events? You can filter out system mouse click events by tapping into CG event tap. But for gestures I have no idea how to filter / disable it

**Comment by e-su** [comment]
Yeah, I want to filter out system mouse click events. I saw hookMouseCallback() and loggerCallback(). I modified some of the code, and it worked as expected! Tapping the left or right side of the trackpad to generate the z or x key without system mouse click events. Thanks, you the boss.
