### ISSUE TITLE
Stops working until reboot after sleep

### ISSUE THREAD

**Issue by ghost** [9tin9tin9/Mac-trackpad-mapper#13]
I'm using macOS 13.5 on a MacBook Air M1, and if I put my Mac to sleep Trackpad Mapper's absolute tracking feature stops working until after I reboot it. I've tried quitting and restarting the app, also killing trackpad_mapper_util, logging out and logging back in again. Only a reboot seems to fix it.

**Comment by ghost** [comment]
I figured out why this is happening. Trackpad Mapper is attempting to set *my Magic Mouse* to absolute tracking mode. If I turn off the mouse and then restart absolute tracking, it works again.

**Comment by lokxii** [comment]
I don't have external trackpads so merging anyways
