### ISSUE TITLE
Accessibility permissions not working despite being granted

### ISSUE THREAD

**Issue by RABBITROAST** [9tin9tin9/Mac-trackpad-mapper#7]
First time on GitHub please bear with

I've loaded everything up as shown, but each time I've attempted to use it, the app asks for accessibility permissions

I hear someone else has also had this issue with Barrier (another app) here: https://apple.stackexchange.com/questions/455212/application-would-like-to-control-this-computer-using-accessibility-features-d

Not sure if it's app specific with this issue, but would like to try using this app if possible. Haven't had this permissions problem with regular apps so far.

Feel free to close if this issue isn't relevant

**Comment by lokxii** [comment]
It worked for me by removing and readding accessibility permission. In fact I do it every time when i do a full recompile and reinstall the application. Not sure why it isn't working on your machine.

**Comment by RABBITROAST** [comment]
Is it possible that Ventura's latest update could contribute to this? It does feel like whatever is preventing the app from functioning is acting silently. 

If you aren't having trouble on the latest Ventura (13.2.1) then I'm also unsure. Will update if I find what works

**Comment by lokxii** [comment]
My mac is currently still on Monterey. I will need to update OS to test

**Comment by lokxii** [comment]
a quick search leads me to [this reddit post](https://www.reddit.com/r/mac/comments/zagc9y/macos_ventura_im_asked_to_add_accessibility/) which leads to [this article](https://www.macworld.com/article/347452/how-to-fix-macos-accessibility-permission-when-an-app-cant-be-enabled.html). Not sure if this helps

**Comment by RABBITROAST** [comment]
> a quick search leads me to [this reddit post](https://www.reddit.com/r/mac/comments/zagc9y/macos_ventura_im_asked_to_add_accessibility/) which leads to [this article](https://www.macworld.com/article/347452/how-to-fix-macos-accessibility-permission-when-an-app-cant-be-enabled.html). Not sure if this helps

no success with this method. My best guess is related to updated security with Ventura which is more likely with the proposed fix being unsuccessful. Will continue to search for a fix

**Comment by RABBITROAST** [comment]
Found a very interesting solution

Dragging the exec file into terminal and giving terminal itself accessibility permissions allows the app to run.
Happy it works, unsure as to why it does.

**Comment by lokxii** [comment]
Good to hear that. Closing this issue now as the solution is found. May reopen if I encounter the issue myself.
