### ISSUE TITLE
App repeatedly asks for accessibility privileges when already granted.

### ISSUE THREAD

**Issue by dawdty** [9tin9tin9/Mac-trackpad-mapper#8]
When enabling absolute tracking a pop-up repeatedly appears asking to grant the app accessibility privileges even though I have already granted them. I thought this may be an issue with how accessibility privileges are managed on Mac, since according to users sometimes they display an incorrect state. So I attempted to reset privileges with `tccutil reset All com.trackpad-mapper` and re-enable but nothing has changed. 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/77356215/230004131-5bf16636-fc11-49fb-9ddc-e709aaa2509d.png">

**Comment by lokxii** [comment]
How about removing Trackpad Mapper from the list first, relaunch the app, grant accessibility again? Not sure why this is the case tbh.

**Comment by skearya** [comment]
i am also facing this problem, i have tried running it through a terminal with the same issue

**Comment by dawdty** [comment]
> How about removing Trackpad Mapper from the list first, relaunch the app, grant accessibility again? Not sure why this is the case tbh.

Forgot to mention I have also tried this.

**Comment by lokxii** [comment]
The newest commit should fix the problem. Please try again

**Comment by skearya** [comment]
it worked, thank you
